# vim: set ft=ansible et ts=2 sw=2:
#
# after OS install and provisioning of standard osticket, this script can be used to apply further specific code modifications
#
---
- hosts: all

  become: True
  become_user: osticket 

  gather_facts: false
  
  vars:

  tasks:

    - name: configure git name, email, and color, just for this repo
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        repo: ~/osTicket
        scope: local
      with_items:
        - { name: 'colour.ui' , value: 'auto' }  
        - { name: 'user.name' , value: 'Vagrant' }  
        - { name: 'user.email' , value: 'nowhere@really.org' }

    - name: run a script, only once though
      shell: |
        echo "said fred" > right.txt
        git checkout -b vagrant-dont-push-me
        git pull --no-edit origin refs/pull/4312/head
        #^ this looks like a nice optimisation, just is third party
        git pull --no-edit origin refs/pull/4229/head
        #^ only useful for non-english but should still work
        git pull --no-edit origin refs/pull/4186/head
        #^ timezone variable fix, could be worth keeping
        git pull --no-edit origin refs/pull/4142/head
        #^ closes a html tag, might not be needed
        git pull --no-edit origin refs/pull/3962/head
        #^ prevent shared xss attachments
        #git pull --no-edit origin refs/pull/3924/head
        #^ require lock for some ticket actions, conflicting :(
        git pull --no-edit origin refs/pull/3893/head
        #^ set session cookies to be unreadable by javascript
        git pull --no-edit origin refs/pull/3562/head
        #^ ticket status in sticky Nav, could be useful still
        git pull --no-edit origin refs/pull/3373/head
        #^ unassign agent when assigning to a team, could be useful still
        git pull --no-edit origin refs/pull/3111/head
        #^ needed for clonemeagain plugins
        git remote add perryk https://github.com/perryk/osTicket.git
        git pull --no-edit perryk fix-missing-agent-welcome-tickbox
        #git pull --no-edit perryk mod-enable-plugin-archiver
        #^ not using this plugin currently
        git pull --no-edit perryk mod-reduce-min-length-agent-phone
        git pull --no-edit perryk mod-remove-rego-check-status-client-page
        git pull --no-edit perryk log-assigned-on-auto-claim-and-set-closing-agent
        ./manage.php deploy /var/www/html/osticket
      args:
        chdir: ~/osTicket
        creates: right.txt

