# vim: set ft=ansible et ts=2 sw=2:
#
# after OS install and provisioning of standard osticket, this script can be used to apply further specific code modifications
#
---
- hosts: all

  become: True
  become_user: osticket 

  gather_facts: false
  
  vars:

  tasks:

    - name: configure git name, email, and color, just for this repo
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        repo: ~/osTicket
        scope: local
      with_items:
        - { name: 'colour.ui' , value: 'auto' }  
        - { name: 'user.name' , value: 'Vagrant' }  
        - { name: 'user.email' , value: 'nowhere@really.org' }

    - name: run a script, only once though
      shell: |
        echo "said fred" > right.txt
        #git checkout -b vagrant-dont-push-me
        #https://github.com/JediKev/osTicket/commit/608dade18ce651bbc4337dc51e9d281637a094c7
        #^ This looks important
        #^ Need to test this
        git pull --no-edit origin refs/pull/4355/head
        #^ This one is important for non-html emails in 1.10.4
        git pull --no-edit origin refs/pull/4351/head
        git pull --no-edit origin refs/pull/4340/head
        #git pull --no-edit origin refs/pull/4312/head
        #^ This looks like a nice optimisation, just is third party
        #^ Need to try this out
        #git pull --no-edit origin refs/pull/4305/head
        #^ Nice feature to show random staff login background
        #^ Need to try this out
        git pull --no-edit origin refs/pull/4284/head
        git pull --no-edit origin refs/pull/4269/head
        #git pull --no-edit origin refs/pull/4265/head
        #^ Currently a conflict on this :(
        # There are other PRs around these number related to php7
        git pull --no-edit origin refs/pull/4256/head
        #git pull --no-edit origin refs/pull/4253/head
        #^ 4253 has now been merged
        #^ This is the fix for the attachments going missing bug
        ##git pull --no-edit origin refs/pull/4239/head
        #^ this is an important fix for saving drafts with attachments
        git pull --no-edit origin refs/pull/4229/head
        git pull --no-edit origin refs/pull/4200/head
        git pull --no-edit origin refs/pull/4186/head
        git pull --no-edit origin refs/pull/4184/head
        #git pull --no-edit origin refs/pull/4183/head
        #^- conflicts with 3956 - only minor vimeo embed fix
        #^- 4183 has been merged now so need to stop using 3956 and fix it somehow
        git pull --no-edit origin refs/pull/4151/head
        git pull --no-edit origin refs/pull/4142/head
        git pull --no-edit origin refs/pull/4124/head
        git pull --no-edit origin refs/pull/4117/head
        git pull --no-edit origin refs/pull/4113/head
        git pull --no-edit origin refs/pull/4111/head
        git pull --no-edit origin refs/pull/4093/head
        git pull --no-edit origin refs/pull/4088/head
        git pull --no-edit origin refs/pull/4086/head
        git pull --no-edit origin refs/pull/4083/head
        git pull --no-edit origin refs/pull/4082/head
        git pull --no-edit origin refs/pull/4061/head
        git pull --no-edit origin refs/pull/4060/head
        git pull --no-edit origin refs/pull/4050/head
        git pull --no-edit origin refs/pull/4049/head
        git pull --no-edit origin refs/pull/4045/head
        git pull --no-edit origin refs/pull/4042/head
        git pull --no-edit origin refs/pull/4040/head
        git pull --no-edit origin refs/pull/4037/head
        git pull --no-edit origin refs/pull/4031/head
        #git pull --no-edit origin refs/pull/4027/head
        #^ This now conflicts and is not needed since 4362
        git pull --no-edit origin refs/pull/4020/head
        git pull --no-edit origin refs/pull/4019/head
        git pull --no-edit origin refs/pull/4018/head
        git pull --no-edit origin refs/pull/4016/head
        git pull --no-edit origin refs/pull/4014/head
        git pull --no-edit origin refs/pull/4012/head
        git pull --no-edit origin refs/pull/4008/head
        git pull --no-edit origin refs/pull/4007/head
        git pull --no-edit origin refs/pull/4002/head
        git pull --no-edit origin refs/pull/4001/head
        git pull --no-edit origin refs/pull/3996/head
        git pull --no-edit origin refs/pull/3983/head
        git pull --no-edit origin refs/pull/3980/head
        git pull --no-edit origin refs/pull/3977/head
        git pull --no-edit origin refs/pull/3976/head
        git pull --no-edit origin refs/pull/3962/head
        git pull --no-edit origin refs/pull/3958/head
        git pull --no-edit origin refs/pull/3955/head
        git pull --no-edit origin refs/pull/3948/head
        git pull --no-edit origin refs/pull/3940/head
        git pull --no-edit origin refs/pull/3931/head
        git pull --no-edit origin refs/pull/3924/head
        git pull --no-edit origin refs/pull/3904/head
        git pull --no-edit origin refs/pull/3901/head
        git pull --no-edit origin refs/pull/3898/head
        git pull --no-edit origin refs/pull/3893/head
        git pull --no-edit origin refs/pull/3889/head
        git pull --no-edit origin refs/pull/3883/head
        git pull --no-edit origin refs/pull/3882/head
        git pull --no-edit origin refs/pull/3875/head
        git pull --no-edit origin refs/pull/3868/head
        git pull --no-edit origin refs/pull/3738/head
        git pull --no-edit origin refs/pull/3628/head
        git pull --no-edit origin refs/pull/3625/head
        git pull --no-edit origin refs/pull/3623/head
        #git pull --no-edit origin refs/pull/3608/head
        #^- this is also included in my mod-onhold-by-nicktheitguy
        git pull --no-edit origin refs/pull/3562/head
        git pull --no-edit origin refs/pull/3543/head
        git pull --no-edit origin refs/pull/3526/head
        git pull --no-edit origin refs/pull/3484/head
        git pull --no-edit origin refs/pull/3456/head
        git pull --no-edit origin refs/pull/3453/head
        git pull --no-edit origin refs/pull/3373/head
        git pull --no-edit origin refs/pull/3111/head
        git remote add perryk https://github.com/perryk/osTicket.git
        git pull --no-edit perryk mod-onhold-by-nicktheitguy
        git pull --no-edit perryk fix-missing-agent-welcome-tickbox
        git pull --no-edit perryk log-assigned-on-auto-claim-and-set-closing-agent
        #git pull --no-edit perryk mod-add-favicon
        #^ now replaced by 4117
        git pull --no-edit perryk mod-allow-agent-emails-to-users
        git pull --no-edit perryk mod-allow-agents-unassign-themselves-from-ticket
        git pull --no-edit perryk mod-enable-plugin-archiver
        git pull --no-edit perryk mod-reduce-min-length-agent-phone
        #git pull --no-edit perryk mod-replace-priority-with-departments
        git pull --no-edit perryk mod-show-offsite-images-by-default
        #git pull --no-edit perryk hardset-brisbane-timezone
        git pull --no-edit perryk mod-remove-rego-check-status-client-page
        ./manage.php deploy /var/www/html/osticket
      args:
        chdir: ~/osTicket
        creates: right.txt

#    - name: copy in a different favicon for use with one of the mods above
#      copy:
#        src:  favicon.png
#        dest: /var/www/html/osticket/favicon.ico
#        owner: osticket
#        group: osticket


