---

- name: restart httpd
  service: name=httpd state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart mariadb
  service: name=mariadb state=restarted
  when: mysql_server_choice == 'mariadb'

- name: restart mysqld
  service: name=mariadb state=restarted
  when: mysql_server_choice == 'mysqld'

- name: run upgrader
